#!/usr/bin/env bash
# Bash equivalent of scripts/build-db-init.ps1 — concatenates the V*.sql
# Flyway migrations into a single file that PostgreSQL can consume.
#
# Used as a fallback when PowerShell is not installed inside WSL.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
SRC="$REPO_ROOT/marry-platform-persistence/src/main/resources/db/migration"
DST="$SCRIPT_DIR/../db-init/00-flyway.sql"

if [ ! -d "$SRC" ]; then
    echo "Migration source not found: $SRC" >&2
    exit 1
fi

shopt -s nullglob
files=( "$SRC"/V*.sql )
shopt -u nullglob
if [ ${#files[@]} -eq 0 ]; then
    echo "No V*.sql migrations found in $SRC" >&2
    exit 1
fi

# Sort by filename (matches Flyway version ordering).
IFS=$'\n' sorted=( $(printf '%s\n' "${files[@]}" | sort) )
unset IFS

{
    echo "-- ============================================================"
    echo "-- Aggregated Flyway migrations for marry-platform"
    echo "-- Auto-generated by deploy/docker/scripts/build-db-init.sh"
    echo "-- Source : marry-platform-persistence/src/main/resources/db/migration"
    echo "-- This file is mounted into postgres:/docker-entrypoint-initdb.d/"
    echo "-- and executed on first DB creation."
    echo "-- ============================================================"
    for f in "${sorted[@]}"; do
        echo ""
        echo "-- ---------- $(basename "$f") ----------"
        echo ""
        cat "$f"
    done
} > "$DST"

echo "Wrote $(wc -c < "$DST") bytes to $DST (merged ${#sorted[@]} migration files)"