# ============================================================
# Aggregates all V*.sql Flyway migrations into a single SQL file
# that PostgreSQL's official image will auto-execute on first start
# (mounted at /docker-entrypoint-initdb.d/).
#
# Source : marry-platform-persistence/src/main/resources/db/migration
# Output : deploy/docker/db-init/00-flyway.sql
# ============================================================

$ErrorActionPreference = 'Stop'

# Force UTF-8 console output so Chinese / Unicode paths print correctly
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding = [System.Text.UTF8Encoding]::new($false)

$src = Join-Path $PSScriptRoot '..\..\..\marry-platform-persistence\src\main\resources\db\migration'
$dst = Join-Path $PSScriptRoot '..\db-init\00-flyway.sql'

if (-not (Test-Path $src)) {
    throw "Migration source not found: $src"
}

$files = Get-ChildItem -Path $src -Filter 'V*.sql' | Sort-Object Name
if ($files.Count -eq 0) {
    throw "No V*.sql migrations found in $src"
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('-- ============================================================')
[void]$sb.AppendLine('-- Aggregated Flyway migrations for marry-platform')
[void]$sb.AppendLine('-- Auto-generated by deploy/docker/scripts/build-db-init.ps1')
[void]$sb.AppendLine('-- Source : marry-platform-persistence/src/main/resources/db/migration')
[void]$sb.AppendLine('-- This file is mounted into postgres:/docker-entrypoint-initdb.d/')
[void]$sb.AppendLine('-- and executed on first DB creation.')
[void]$sb.AppendLine('-- ============================================================')

foreach ($f in $files) {
    [void]$sb.AppendLine()
    [void]$sb.AppendLine("-- ---------- $($f.Name) ----------")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine((Get-Content -Raw $f.FullName))
}

Set-Content -Path $dst -Value $sb.ToString() -Encoding utf8

Write-Host ("Wrote {0} bytes to {1} (merged {2} migration files)" -f $sb.Length, $dst, $files.Count)
